config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'signup'
  }

  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: redirect('/home')
  get 'home', to: 'pages#home', as: 'home'

  # BuildPC Routes
  get 'build', to: 'pages#build', as: 'build'
  resources :build_pcs, path: 'build', only: %i[new create edit update]

  # Cart Routes
  get '/cart', to: 'cart#show', as: 'cart'
  delete '/cart', to: 'cart#destroy'

  # Cart Items Routes
  post '/cart_items', to: 'cart_items#create', as: :cart_items
  delete '/cart_items/:id', to: 'cart_items#destroy', as: :cart_item
  post '/checkout', to: 'cart#checkout', as: 'checkout'

  # Accessories Routes
  get 'accessories', to: 'pages#accessories', as: 'accessories'
  get '/accessories/:accessory_name', to: 'accessories#show', as: 'accessory'

  get '/keyboards', to: 'accessories#keyboards', as: 'keyboards'
  get '/mouses', to: 'accessories#mouses', as: 'mouses'
  get '/chairs', to: 'accessories#chairs', as: 'chairs'
  get '/monitors', to: 'accessories#monitors', as: 'monitors'
  get '/headsets', to: 'accessories#headsets', as: 'headsets'
  get '/webcams', to: 'accessories#webcams', as: 'webcams'

  # ReadyToShipPC Routes
  get 'readytoship', to: 'pages#readytoship', as: 'readytoship'
  get 'readytoship/:id', to: 'pages#rtsshow', as: 'readytoships'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTemplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

 

<nav class="main-nav">
  <div class="nav-left">
    <%= link_to home_path, class: "nav-item" do %>
      <%= image_tag "fast-pcs.png", alt: "FAST PC's Logo", style: "height: 50px;" %>
    <% end %>

      <% if user_signed_in?%>
        <%=  link_to 'Cart', cart_path, class: 'nav-item' %>
      <% end%>
  </div>


    <div class="nav-right">
      <% if user_signed_in? %>
        <span class="nav-item">Welcome <%= current_user.username %></span>
        <%= button_to "Sign Out",
                      destroy_user_session_path,
                      method: :delete,
                      class: "nav-item nav-button" %>
      <% else %>
        <%= link_to "Login",
                    new_user_session_path,
                    class: "nav-item" %>
        <%= link_to "Sign Up",
                    new_user_registration_path,
                    class: "nav-item" %>
      <% end %>
    </div>
  </nav>



      <%= yield %>
    </main>
  </body>
</html>